### ISSUE TITLE
User UI for viewing past and existing SSL certificates

### ISSUE THREAD

**Issue by cychu42** [DevelopingSpace/starchart#10]
It would be nice to have an UI to display all the SSL certificates for a user, in case they need to view the information. The UI can include:
- Status of a certificate (e.g., complete, failed, expired...etc.)
- A link to retrieve a certificate
- Information regarding a certificate (e.g., expiration date, domain...etc.)

We can allow sorting for better experience.

**Comment by humphd** [comment]
I think this is done now, do we need this issue open still?

cc @Ririio

**Comment by Ririio** [comment]
It should be done now, I only need to connect it with the back end
