### ISSUE TITLE
Use logger module throughout our server code

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#104]
Now that #93 is in, we have `lib/logger.server.ts` available to all of our server code.  I'd like to see us use it to add proper debug, info, warn, error, style logs.

We should prefer to use `debug` for most things, and only bother with `info` when absolutely necessary (e.g., in production, we don't need to log normal behaviour).  We should use `warn` for cases where we handle the error, and leave `error` for actual errors that we want to know about in production.

**Comment by SerpentBytes** [comment]
@humphd, Since we are no longer using `pino`, is it safe to close this issue?

**Comment by humphd** [comment]
No, I still want this, just using the new logger vs. pino.  I've updated the title.

**Comment by humphd** [comment]
We're doing this all over now.
