### ISSUE TITLE
UI Design for Admin Dashboard

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#106]
When a user logs in, if they are an Administrator, we need to give them a different dashboard page.  This should include a few things:

1. Metrics.  It would be great to surface a few key metrics.  For example: how many users are in the system?  How many domains do they have?  How many certificates?  There are probably a few more, but we don't need a ton of this.  We also don't need complicated graphs or to make this into something huge.  Let's show a few numbers that have meaning.
2. List of Users.  It would be ideal for an admin to be able to see the list of all users.  This list could get long, so we may need to page it.
3. Become a User.  @dadolhay had a great suggestion: let an admin assume the role of a given user.  This is nice because we can then make various adjustments to a user's account/domains/certs without adding new UI. When an admin is logged in as another use, it would be good to alter the UI somehow (different colour? different nav bar? etc) so that it indicates it, and allow them to get back out to their own account.

There might be more we need to do, but this is likely a good start.

**Comment by humphd** [comment]
@Ririio, @Eakam1007, or @Myrfion does one of you want to take this?

**Comment by Myrfion** [comment]
@humphd  Does it make sense to make it on a single page or split it into several?

**Comment by humphd** [comment]
@Myrfion I think when you arrive as an admin, we should have some "cards" or something with a few high level metrics, and then maybe a paged table of users that you can become?  Not sure.  Probably one page is enough.  But I'm open to your suggestion.

**Comment by Ririio** [comment]
How about for displaying we can have a button that switches from a card to a list? We can display a specific amount which the admin can cycle through, the quantity display depends on the state, obviously the list would be higher in count...

**Comment by Myrfion** [comment]
Completed in Figma
