### ISSUE TITLE
Include link to Seneca's ITS Acceptable Use Policy in UI somehow

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#107]
Seneca has asked that we somehow include a way to remind the user about [Seneca's ITS Acceptable Use Policy](https://www.senecacollege.ca/about/policies/information-technology-acceptable-use-policy.html).  Probably having a link, and letting users know about how this affects them.  For example, you can't:

- use IT Resources for personal commercial or financial gain
- access, create, publish or communicate information that is obscene, pornographic, abusive, defamatory, derogatory, threatening, violent or harassing, including material that may interfere with other individuals’ rights under the Human Rights Code or the Occupational Health and Safety Act
- create, distribute and/or link to offending materials that conflict with rights and interests protected by Canadian Charter of Rights and Freedoms, the Human Rights Code or the Criminal Code
- use IT Resources for any purpose that violate the Criminal Code
- use IT Resources for any purpose (e.g. upload material) that is not in accordance with the Copyright Act, Seneca’s Copyright Policy and Fair Dealing Policy for Copyright-Protected Work

It's not up to us to include all this, but we should link to it.  Maybe that means we put it in the page footer?  This needs some thought.

**Comment by Ririio** [comment]
The user will be on the landing page when they login. We can add a container underneath the cards, and have a sentence or two in regards to the policy. Then we insert a link for "more" informations? Just a thought...

We need more informations on the footer if we're thinking of adding the policy there. Not keen on creating it for the sake of one singular functionality.

**Comment by humphd** [comment]
Here's a proposal.  Put a sentence with a link at the bottom of this page (where I have the box):

<img width="1047" alt="Screenshot 2023-03-31 at 12 14 05 PM" src="https://user-images.githubusercontent.com/427398/229174535-eb6c57a0-aeb3-4611-a8c1-064f8f028427.png">

It can say something like:

> My.Custom.Domain is meant for educational use only by Seneca students and faculty, and is governed by Seneca's IT Acceptable Use Policy.

You can make `Seneca's IT Acceptable Use Policy` a link to https://www.senecacollege.ca/about/policies/information-technology-acceptable-use-policy.html

**Comment by humphd** [comment]
No, people using this won't care about all that stuff (we do, because we're building it). This text I want is different.
