### ISSUE TITLE
Enforce a configurable limit on the number of DNS records per user

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#110]
We need to be able to set an environment variable that imposes a limit on the number of DNS records a user can have.  When the user tries to add a new record, their current record count should be compared against this limit, and the operation should fail if it will mean exceeding the limit.

I'm not sure what the right way to enforce this is (e.g., in the db, in the model code, etc).

**Comment by Genne23v** [comment]
In my opinion, if model declines the request, queue will continuously request although there is no second chance to make it happen. I think the dns worker should throw `UnrecoverableError`. Please let me know if it sounds like a plan.
