### ISSUE TITLE
Indicate how many more DNS records a user can create in the UI

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#111]
In #110 we're adding a limit to the number of DNS records a user can have.  We should indicate how many more records a user can create before hitting this limit in the UI.  This will help users understand what is happening with their account.

**Comment by sirinoks** [comment]
Will we need to add this in a front end component somewhere?
And if so, will we need to store this infromation in the database too?

**Comment by humphd** [comment]
#413 is connected to this.
