### ISSUE TITLE
Feat: Domains Table

### ISSUE THREAD

**Issue by Myrfion** [DevelopingSpace/starchart#137]
### Overview
This task aims to create a component named `DomainsList.tsx` that will render domains list and trigger certain actions.  

### Design
Refer to Figma for the design

### Implementation
Table should be done with Chakra UI table: https://chakra-ui.com/docs/components/table

Props should look something like:
```typescript
interface DomainsListProps {
 domains: Domain[]
 onAction: (action: DomainsListAction) => void
}

type DomainsListAction = 'EDIT' | 'DELETE' | 'RENEW'  
```

**Comment by humphd** [comment]
I would use `RENEW` vs. `REFRESH` to better reflect what it does.

**Comment by Eakam1007** [comment]
Is this a duplicate of #46 ?
