### ISSUE TITLE
Create a consistent label structure that outlines project categories

### ISSUE THREAD

**Issue by sirinoks** [DevelopingSpace/starchart#141]
We have this [doc with tasks](https://github.com/Seneca-CDOT/starchart/wiki/Initial-Task-List-and-Scope#tasks).

We should connect those from "Category" column to our labels. In [Telescope](https://github.com/Seneca-CDOT/telescope/labels) we have such a thing, with "area:" added. We might want to keep the same naming here, or rename it. But it needs to stay consistent so that people know what is what.

We already have some labels that do this, so we would just need to make a specific format and make sure they all correspond with it.

I want to do this, but I also want people's suggestions on how to name the category. Is "area" fine, or do we want something else?

**Comment by sirinoks** [comment]
Since nobody really said anything, I will use both `area` and `category` for different grades of detalisation. The goal here is to keep things consistent. So, I will make "areas" as more major directions. While "categories" will be more concrete, perhaps, services. Just keep in mind that areas are bigger.

**Comment by humphd** [comment]
These have been in use for a while, closing at this stage and we can fix things on the go as needed.
