### ISSUE TITLE
Provide Emergency Shutdown (Panic Button) functionality

### ISSUE THREAD

**Issue by ctyler** [DevelopingSpace/starchart#142]
In the event of a systems breach (e.g., through compromised secrets, or holes in auth libraries), a Bad Actor could potentially wreak a lot of chaos. It would be useful to have a mechanism to globally shut down the system in an emergency in such a way that it can't be overridden by the (compromised) API, and which would more positively disable active resource records (as opposed to no longer serving them authoritatively and waiting for them to eventually timeout across layers of caches).

**Comment by humphd** [comment]
Thanks for filing this.  What sort of mechanism do you imagine this being?  What does the workflow look like?

**Comment by humphd** [comment]
I'm not clear what action to take here and don't have further feedback.  Closing for now, but feel free to re-open or file something new if you want to explore.
