### ISSUE TITLE
Create BULLMQ queue structure (with skeletons) to create a certificate

### ISSUE THREAD

**Issue by dadolhay** [DevelopingSpace/starchart#167]
We need four (nested) steps

In *reverse order, from child to parent*:
- Create order (add DNS records)
- Wait for DNS propagation
- Confirm challenges with the ACME provider
- Finish the order, clean up DNS

Resources:
https://docs.bullmq.io/guide/flows
https://github.com/Seneca-CDOT/starchart/pull/161

**Comment by humphd** [comment]
For others reviewing/working on this, https://blog.taskforce.sh/splitting-heavy-jobs-using-bullmq-flows/ is a useful example of a similar flow layout with multiple queues.

**Comment by dadolhay** [comment]
> For others reviewing/working on this, https://blog.taskforce.sh/splitting-heavy-jobs-using-bullmq-flows/ is a useful example of a similar flow layout with multiple queues.

Looks interesting! I'll check it out!
