### ISSUE TITLE
Create Users in Prisma Seed

### ISSUE THREAD

**Issue by sfrunza13** [DevelopingSpace/starchart#175]
As a follow up to #105 and #174 this issue aims to add 3 new users to seed. 2 of these users can be in the database and one of them should be used for the first time login case.

**Comment by cychu42** [comment]
What would be the difference between the 2 and the 1 left out from perspective of the database? Do you mean 1 of them should be a row on user table but no other related data (e.g., certificate)?

**Comment by humphd** [comment]
The idea being:

- 2 users who are already in our system, and we can seed with various kinds of data
- 1 user who is not, and we can use to test "first time signup" flows
