### ISSUE TITLE
Stop Dependabot from using node versions updates

### ISSUE THREAD

**Issue by SerpentBytes** [DevelopingSpace/starchart#199]
## Description
 >  @SerpentBytes we should figure out how to stop this from using non-LTS node versions.

_Originally posted by @humphd in https://github.com/DevelopingSpace/starchart/issues/194#issuecomment-1428180746_

**Comment by humphd** [comment]
I think this is going to be hard: https://github.com/dependabot/dependabot-core/issues/2247

**Comment by SerpentBytes** [comment]
> I think this is going to be hard: [dependabot/dependabot-core#2247](https://github.com/dependabot/dependabot-core/issues/2247)

Yes, I was looking at this thread earlier. We could start by avoiding all `node` version updates for Docker and then narrow down LTS. I also searched for a way to tell whether a version is LTS based on version numbering, but there's no luck there. . We could fetch from this endpoint: `https://nodejs.org/download/release/index.json` and filter the result by LTS. Then we can somehow specify it in Dependabot config (if possible)
See:
https://stackoverflow.com/questions/71518977/how-do-i-programmatically-check-the-release-status-of-the-installed-node-js-vers

I'll do some more research and report my findings.

**Comment by humphd** [comment]
I think we should just ignore node images, and handle it manually.  It's not a surprise when LTS changes.
