### ISSUE TITLE
Header is not responsive

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#202]
The header isn't working on smaller viewport sizes.  We should get it working on any screen size.

<img width="391" alt="Screenshot 2023-02-13 at 8 17 17 PM" src="https://user-images.githubusercontent.com/427398/218613185-893283c8-abbb-467a-a1cf-aaae6d7f5d67.png">

**Comment by Ririio** [comment]
I didn't considered this during the development process. Can I be assigned for this to fix the issue?

**Comment by humphd** [comment]
@Ririio you never need to ask, go ahead and fix any/all bugs we have.

**Comment by Genne23v** [comment]
Closed with #212
