### ISSUE TITLE
Implement landing-page experience

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#204]
When a user logs in, we take them to an empty page at `/`.  A user essentially has `/domains` and `/certificate`.  What should we do at `/`?

We could provide a landing page that does something similar to Amazon Cognito (i.e., provide some text, and a "cards" that take you to "Domains" and "Certificate"):

![image](https://user-images.githubusercontent.com/427398/218614543-332747a3-9416-4aeb-adea-b862d588f0c5.png)

We could also drop you directly into your Domains page.  We need to think about it.

**Comment by Ririio** [comment]
Just wondering. The header still appears at this page right?

**Comment by Eakam1007** [comment]
Yup, I am pretty sure it should

**Comment by Ririio** [comment]
I like the idea of providing information within this page. Either as a small boxes referring to what "certificate" and "domain" does? We can have a "simplify" version of what they are, and split it across a "next" and "previous" functions. If they want a much deeper understanding we send them to a link with a much more robust information?

**Comment by Ririio** [comment]
What information are we suppose to provide within the card that you mentioned @humphd?

**Comment by humphd** [comment]
@Ririio you could include the icons and titles for DNS Records and Certificates, and below, provide a sentence or two about what each one is for.

**Comment by Ririio** [comment]
You're referring to icons like these right?

![image](https://user-images.githubusercontent.com/32577022/223574278-b01adb3e-f1be-4610-a216-9339f3939a60.png)

**Comment by humphd** [comment]
The current icons you use in the header.
