### ISSUE TITLE
Provide tooltips for domains table icons

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#205]
We have a bunch of icons in each row for a domain:

<img width="324" alt="Screenshot 2023-02-13 at 8 31 16 PM" src="https://user-images.githubusercontent.com/427398/218614966-383fd6e1-3aa5-4d67-987c-8e3d64232f24.png">

Hovering over these doesn't tell you what they are.  Let's include a tooltip or HTML title or something.

**Comment by Myrfion** [comment]
Fixed in #276
