### ISSUE TITLE
Improve styling of Domains table bottom

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#211]
I don't like the two lines at the bottom of the table (one for the last row, one for the card border):

<img width="1274" alt="Screenshot 2023-02-14 at 10 41 19 AM" src="https://user-images.githubusercontent.com/427398/218786173-5c5593a4-371f-43c4-a039-b6f0cda186b8.png">

Can we improve this somehow?

**Comment by Myrfion** [comment]
Easies option that will make it look better in my opinion is just removing the bottom line of the last row

**Comment by humphd** [comment]
@Myrfion sounds good, can you take this since you're active on this code?

**Comment by Myrfion** [comment]
yep

**Comment by Ririio** [comment]
Looking at the local repo, the lines doesn't exist anymore, am I safe to assume that this issue has been solved?
