### ISSUE TITLE
Replace prettier check action with our own script

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#239]
The prettier check action we use, `creyD/prettier_action`, keeps randomly failing: 

```
Run creyD/prettier_action@v4.2
Run PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh
Installing prettier...
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found
Problem running prettier with --check .
Error: Process completed with exit code 1.
```

Let's replace it with a call to [`prettier --check`](https://prettier.io/docs/en/cli.html#--check) adding a script to `package.json`.

**Comment by shawnyu5** [comment]
This seems to have started happening recently. There is a bug report on the prettier actions repo. The advantage of using this is its way faster than installing prettier ourselves, and running `prettier --check`

https://github.com/creyD/prettier_action/issues/113

**Comment by shawnyu5** [comment]
There seems to be a fix in progress? It seems like the ubuntu image bumped up their npm version, which changed some npm paths. Lets see where this leads. 

https://github.com/creyD/prettier_action/pull/112

**Comment by humphd** [comment]
Sounds good, thanks for researching.

Remember the discussion about why I want to pin image/dependency versions?  It's because of bugs like this, where a version of `npm` gets bumped, and causes a chain reaction of failures in other parts of the app.
