### ISSUE TITLE
Sign in does not work on Safari

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#244]
### Local Environment
After clicking the `Sign In` button to localhost on safari, the following is shown. Safari uses `https` but even after manually changing it to `http`, the login page is shown again:
(Video provided by @Genne23v)

https://user-images.githubusercontent.com/67077705/219962357-4baa7cdf-bfab-4b07-86de-0ace58612c95.mp4

### Test Environment

This also resulted in these failed tests: https://github.com/DevelopingSpace/starchart/actions/runs/4213508191. The tests fail for Desktop (webkit) and Mobile Safari
> Please ignore the failed test for chrome since that was due to missing wait time for sign in.

A video of the failed test run, taken from the above link (download the `playwright report` artifact, look under failed tests, and retry#1)

https://user-images.githubusercontent.com/67077705/219923031-5418df78-3aed-438c-8659-cfeaded30696.mp4

Some investigation is required to find out what is happening here. It seems like the Sign in button is clicked but no redirect happens.

**Comment by humphd** [comment]
Why are you using `https`?

**Comment by Eakam1007** [comment]
Oh, I missed that yesterday. My guess is safari defaults to `https`. Will have to check this again by manually specifying `http`

However, for the test environment, the base url does not use https:
```baseURL: `http://localhost:${process.env.PORT}`,```

**Comment by Eakam1007** [comment]
I have updated the screenshot with a video as per [this discussion](https://seneca-open-source.slack.com/archives/C04HR4WV5P0/p1676764252754789)

Safari changes `http` to `https` after the Sign in button is clicked, and does not redirect to home page

**Comment by humphd** [comment]
I think this is CSP related.  We are sending the `upgrade-insecure-requests` header.  Do you want to try doing this in `server.ts`, see https://github.com/DevelopingSpace/starchart/blob/main/server.ts#L29-L41:

```ts
helmet.contentSecurityPolicy({
    useDefaults: false,
    directives: {
      ...
      upgradeInsecureRequests: null,
    },
  })
```

That would disable it, and if it works, we could then make it work only for development.

**Comment by Eakam1007** [comment]
Hmmm, doesn't seem to work in the testing environment
