### ISSUE TITLE
Standardize on naming for Domain vs. Record

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#245]
All over the code we use Record and Domain in various contexts.  I'm reviewing code right now that does this:

```ts
function onDomainAction(domain: Record, action: DomainsTableAction) {
```

This seems odd to me.  Can we come-up with a standard way to deal with this through the code and normalize our types/names?

**Comment by Eakam1007** [comment]
We probably should use `Record` instead of `Domain`

**Comment by humphd** [comment]
I think `Record` is too vague.  A `Record` makes sense only if you already understand the context, but it can be confused with a record in a database, etc.  I propose we call these `DNS Records` (in UI) and `DnsRecord` in code and the database.

Prior art:

- https://www.cloudflare.com/learning/dns/dns-records/
- https://ns1.com/resources/dns-records-explained

**Comment by humphd** [comment]
We should get this done in the next release if possible, so that it doesn't drag out.
