### ISSUE TITLE
Deal with `.` in usernames when generating domain names

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#253]
There are 3 types of users in our SSO system:

1. students (whatever@myseneca.ca)
2. and 3. faculty and staff (what.ever@senecacollege.ca)

The latter will include a `.` in the username.

We'll need to deal with this somehow.  We could remove it, such that `david.humphrey` becomes `davidhumphrey`.  We could replace it `david.humphrey` becomes `david-humphrey` or `david_humphrey`.

If we remove it, there is a slight chance that the name could collide with a student name.  We'd have to figure out how to deal with that error.

**Comment by cychu42** [comment]
I thought student emails always use a shorten name that might come with a number, while professors' are just full names.

**Comment by humphd** [comment]
The issue I'm talking about is the internal `.` in an employee's username.  The rest doesn't matter, but students won't ever have it afaik.

**Comment by cychu42** [comment]
Please correct me if I'm wrong. Isn’t the part before `@` the username? My point being that a `david humphrey` as a student would get `dhumphrey` from Seneca, while a professor gets `david.humphrey` which can be `davidhumphrey` in our system. And there’s no confusion.

If we are to replace the `.`, we can consider using a less used symbol to replace the `.`, such as `~` or `|`.
I have seen students with `-` in the username.

**Comment by humphd** [comment]
Yes, the part before `@` in an email.  I agree, we can try to simply drop the `.` and hope for no collisions.  I think it's very unlikely, for the reason you list.

**Comment by humphd** [comment]
To clarify this: we need to take the `sAMAccountName` value we get back from Seneca's SSO SAML response, and deal with any invalid DNS characters.  I'm only aware of `.` being an issue at the moment, but we could probably use the name validation logic @Genne23v wrote for our Route 53 code to test things.
