### ISSUE TITLE
Add appropriate connect to records service to make record prolonging work

### ISSUE THREAD

**Issue by Myrfion** [DevelopingSpace/starchart#281]
Same as #280 but for prolonging expiratory day of record

**Comment by humphd** [comment]
@Eakam1007 is this working now?

**Comment by Eakam1007** [comment]
Seems like this only updates the DNS Record expiry date in the Database. Also, it is always setting the month to "July" no matter what date the current expiry/creation date is:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/67077705/227790229-06405ffa-c2ca-488d-abc2-a6093dfb663a.png">
