### ISSUE TITLE
Configurability to different env (dev, staging, prod)

### ISSUE THREAD

**Issue by Genne23v** [DevelopingSpace/starchart#29]
We need to be able to configure different env setting. Following items need to be considered in the configuration

- User authentication (dev vs. staging, prod)
- Test database for dev
- Need staging database separate from prod?
- Env variables (dev / staging / prod)
- Settings for `docker-compose` (dev vs staging, prod)
- Endpoint settings ( dev vs. staging / prod)

**Comment by humphd** [comment]
This is all done now.
