### ISSUE TITLE
Access Denied / Login Failed Page

### ISSUE THREAD

**Issue by sfrunza13** [DevelopingSpace/starchart#292]
I would like to have a front end representation of a failed login. We made it to the callback but did not succeed in creating a user / session so then I need to redirect to a problem.

```
  // Try and extract the username and see if there is an existing user by that name
  if (!samlResponse.attributes.sAMAccountName) {
    // TODO: Make this redirect to access denied page
    return redirect('/');
  }
```

The redirect here would be to the new route that would display an error message for the user.

**Comment by Ririio** [comment]
How do I recreate this process on my local repo?

**Comment by sfrunza13** [comment]
```
'broken:ithurts' => array(
        'uid' => array('2'),
        'eduPersonAffiliation' => array('group2'),
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress' => 'broken.heart@myseneca.ca',
        'email' => 'hansolo@myseneca.ca',
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname' => 'broken',
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname' => 'heart',
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'=> 'broken.heart@myseneca.ca',
        'http://schemas.microsoft.com/identity/claims/displayname' => 'Broken Heart',
        
    ),
```

Add this to the users config, it does not have a samaccountname and will hit exactly that redirect

**Comment by sfrunza13** [comment]
The saml response comes from the IDP as part of one of the bindings, it's posted to us at this callback route. The following function on the callback is what is responsible to parsing the body and returning the samlResponse object that we later work with:
`const { samlResponse, relayState } = await parseLoginResponse(body);`

**Comment by sfrunza13** [comment]
Something similar to that would be fine, I just want a page that displays to the user that something went wrong when signing in. Keeping it vague is ok.
