### ISSUE TITLE
Put instructions for certificates

### ISSUE THREAD

**Issue by Myrfion** [DevelopingSpace/starchart#293]
We have much blank text on different pages such as:
- domains screen description
- domain creation/editing 
- certificate (before it was created and after)

All these should be replaced with the meaningful text that will help user to figure out what is going on

**Comment by humphd** [comment]
See also #388, which might be the same bug.

**Comment by Myrfion** [comment]
Related #443

**Comment by humphd** [comment]
See https://dev.to/genne23v/what-is-dns-record-1cbk for a starting point.
