### ISSUE TITLE
Include docs on how to understand and debug e2e tests

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#295]
I am looking at an e2e test failure in #294, see https://github.com/DevelopingSpace/starchart/actions/runs/4348577165

Playwright gives us so much good info and tooling to debug this, and we should document it so others know how to use it.

For example, at the bottom of the GitHub Action, there is a link to download a `playwright-report.zip` file:

<img width="937" alt="Screenshot 2023-03-06 at 6 40 46 PM" src="https://user-images.githubusercontent.com/427398/223283380-0b5aeebb-c7f9-49f7-8099-334ea893499d.png">

This file expands to a folder containing:

1. `index.html`-> a web app that shows all the details of the test runs
2. `data/` -> a folder of videos and `.zip` traces for all of the failed tests

The videos you can play in your browser, and it shows the test running in the browser.  Often you can see what is failing.  However, to get even more detail, you can use the amazing [Trace Viewer](https://playwright.dev/docs/trace-viewer):

```
npx playwright show-trace trace.zip
```

This lets you do all kinds of debugging after the fact, seeing exactly what happened in the test.  It's amazing.

Let's document this so people understand how to use it all.

**Comment by humphd** [comment]
Also add info on debugging visually https://playwright.dev/docs/debug

**Comment by Eakam1007** [comment]
Should we put this on the wiki? Or in `CONTRIBUTING.md`

**Comment by humphd** [comment]
Docs in Wiki with link to it in CONTRIB is fine

**Comment by Eakam1007** [comment]
Alright, I will try adding it there sometime this week

**Comment by humphd** [comment]
These videos are amazing:

- How to use Trace Viewer - https://www.youtube.com/watch?v=lfxjs--9ZQs
- How to Debug - https://www.youtube.com/watch?v=tJF7UhA59Gc
- etc
