### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Genne23v** [DevelopingSpace/starchart#30]
`README` needs to be updated for users, developers, contributors. `README` should display below contents for easy understanding of what `starchart` is, how to use, how to contribute, etc. 

- Introduction 
- Links and badges if necessary
- Background
- How to use
- Links for developers (setup, contribution rules, where to discuss)
- License
- etc.

**Comment by shawnyu5** [comment]
relates to #13

**Comment by humphd** [comment]
I think this can be closed, and #136 or other specific issues can be filed going forward.
