### ISSUE TITLE
Display DNS record description in a tooltip

### ISSUE THREAD

**Issue by SerpentBytes** [DevelopingSpace/starchart#304]
@humphd on [Slack](https://seneca-open-source.slack.com/archives/C04HR4WV5P0/p1678194333718579):

<img width="622" alt="Screenshot 2023-03-08 at 11 19 22 AM" src="https://user-images.githubusercontent.com/50856799/223769238-b4881f53-9832-4722-a6a1-55873751dc16.png">

## Details
We should place all the optional info and display it in a tooltip. Doing this would make the view more compact, and the relevant information would be hard to miss.

**Comment by Ririio** [comment]
If you don't mind me asking, you're referring to having a tool tip when you're hovering on top of any information (icons or not), which the user might want to learn about right?

**Comment by humphd** [comment]
When you hover on that blue dialog-bubble icon.

**Comment by Ririio** [comment]
Would this replace the already existing tooltip to make it more compact and hard to miss?

**Comment by humphd** [comment]
No, it's a separate thing.  We don't show that optional data in the table right now, but something like the above would let us include it.
