### ISSUE TITLE
Allow users to be deactivated

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#308]
While discussing the deletion of users based on the design for the Admin UI (#106), it was concluded that deletion would be a multi step process. The first step in this would set a flag on the user that is being deleted, effectively setting the user as `deactivated`. This would prevent users from being able to perform actions while their account is being deleted.

Further, while checking if a user is logged in (username is present in the session), we should only return the user if the flag is not set (the flag for `deactivated` is false for the user). This is to handle the case where a user gets deleted from the database but is still logged in (i.e. their session has not expired).

At minimum, the following needs to be done:
- Update the schema to add a `deactivated` flag to the user model
- Update `requireUsername` and `requireUser` methods to check for the flag and not return the username if the user is `deactivated`
- Add/update tests as needed

**Comment by dadolhay** [comment]
Looks good!

Also, each worker (except cleanup) should do the same verification of the user being present in DB and is not being deleted.
If the user is, whould throw an IrrecoverableError from BullMQ

**Comment by Eakam1007** [comment]
#318 is a part of this
