### ISSUE TITLE
Add utility function for creating future dates

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#311]
In a whole bunch of places, we have code for creating future dates.  It often looks like this:

```ts
  let monthFromToday = new Date();
  monthFromToday.setMonth(monthFromToday.getMonth() + 1);
```

Let's write a function in `app/utils.ts` that lets us do this once.  There might be a simple dependency we can use too.

**Comment by SerpentBytes** [comment]
We could use [Day.js](https://www.npmjs.com/package/dayjs) to manipulate dates like:
```js
dayjs().set('month', 3).month() 
```

**Comment by humphd** [comment]
Yeah, that works.  It might be good to just replace all of our code for creating future dates with that vs. making a new function.

**Comment by SerpentBytes** [comment]
Already using Day.js in #268

**Comment by humphd** [comment]
I think using day.js is good enough
