### ISSUE TITLE
Poll for Certificate update when being created

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#317]
Similar to #316, the front-end should poll for status changes when a Certificate is being created and not all data is available yet.  Once the certificate is fully available in the db, there is no reason to bother any more.

We can do this in Remix with [useRevalidator](https://remix.run/docs/en/1.14.1/hooks/use-revalidator).

**Comment by humphd** [comment]
See my work in https://github.com/DevelopingSpace/starchart/pull/355 for a pattern to follow.

**Comment by humphd** [comment]
@Ririio are you going to solve this in your cert UI stuff?

**Comment by Ririio** [comment]
Oh checking if status has changed, yes I'm doing that

**Comment by humphd** [comment]
This is being done in #434, closing.
