### ISSUE TITLE
Adding an "active" flag to User model

### ISSUE THREAD

**Issue by cychu42** [DevelopingSpace/starchart#318]
As discussed in this week's meeting on Wednesday March 8, we should have an `active` column in `User` model to act as a flag, when we need to shutdown access of a user.

We would need to modify:
* `prisma\schema.prisma` for the schema
* `prisma\seed.ts` for seeding
* `app\models\user.server.ts` for functions to set and check whether someone is active

**Comment by humphd** [comment]
I'd consider making it a negative vs positive: `flagged` vs. `active`.  We want to indicate that a user is in some special state.
