### ISSUE TITLE
Fix Remix deprecation warnings

### ISSUE THREAD

**Issue by sfrunza13** [DevelopingSpace/starchart#320]
Remix is deprecating the old nested folders route convention in favor of "flat routes" in v2. There will be a helper function to use the old convention in v2 but they recommend making the change to the newer convention now and making the jump to v2 easier in the future.

https://remix.run/docs/en/main/file-conventions/route-files-v2

I believe this is the 'flat-routes' in question https://github.com/kiliman/remix-flat-routes

`.` in file name becomes a `/` in the route example: `concerts.trending.tsx` = `/concerts/trending`
`$` is used for dynamic data like ids example: `users.$id.tsx`  = `/users/12`

you can also create a folder and treat it as a flat file by appending `+` to it
`_auth+/forgot-password.tsx => _auth.forgot-password.tsx`

It is apparently possible to migrate our existing routes: https://github.com/kiliman/remix-flat-routes#-migrating-existing-routes

**Comment by humphd** [comment]
Updating Remix last night, there are a few more to figure out:

>⚠️ REMIX FUTURE CHANGE: The behaviors of `CatchBoundary` and `ErrorBoundary` are changing in v2. You can prepare for this change at your convenience with the `v2_errorBoundary` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#catchboundary-and-errorboundary
>⚠️ REMIX FUTURE CHANGE: APIs that provide `formMethod` will be changing in v2. All values will be uppercase (GET, POST, etc.) instead of lowercase (get, post, etc.) You can prepare for this change at your convenience with the `v2_normalizeFormMethod` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#formMethod
>⚠️ REMIX FUTURE CHANGE: The route `meta` export signature is changing in v2You can prepare for this change at your convenience with the `v2_meta` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#meta
>⚠️ REMIX FUTURE CHANGE: The route file convention is changing in v2. You can prepare for this change at your convenience with the `v2_routeConvention` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#file-system-route-convention
