### ISSUE TITLE
Don't list certificate challenge records for the end-user

### ISSUE THREAD

**Issue by dadolhay** [DevelopingSpace/starchart#332]
Exclude records from the user-facing record UI if type is TXT and subdomain is `_acme-challenge`

**Comment by humphd** [comment]
@Myrfion this is something you might want to do, since it's in the code you've been writing.  If `dnsRecord.subdomain === '_acme-challenge'`, skip showing it in the table.

**Comment by humphd** [comment]
Filed https://github.com/DevelopingSpace/starchart/issues/413 on dealing with these records in the user's limit.

**Comment by Ririio** [comment]
Did we already merge a PR for this issue?

**Comment by humphd** [comment]
Fixed by #424, which covered #413 and this at the same time.
