### ISSUE TITLE
Improve anchor text accessibility on landing page

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#341]
<img width="791" alt="Screenshot 2023-03-14 at 5 39 57 PM" src="https://user-images.githubusercontent.com/427398/225145182-44c48aef-a6fb-4cf0-9150-a15365407ff0.png">

The light blue text colour for links is not using enough contrast.  I think we need to pick something else.  Does blue even go with your colour theme?

cc @Myrfion

**Comment by Eakam1007** [comment]
Maybe we could use a different shade of blue? A shade of red might look too much like the shade for a link that has already been visited

**Comment by humphd** [comment]
Or use an underline and slightly different "black" to keep with the theme.  Someone should look into how other apps with our same palette solve this.

**Comment by Eakam1007** [comment]
Oh, I think that is similar to what Seneca uses elsewhere as well, such as blackboard:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/67077705/226379796-ca68eae4-bf46-4399-9c0e-1c7d7e9f95a4.png">
I will look in to this to confirm if this is the case everywhere
