### ISSUE TITLE
Missing `.`s in domain display

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#359]
In the Domains table, we are showing a user's domains, but they are missing all the `.`s except for the first one:

<img width="338" alt="Screenshot 2023-03-16 at 4 34 31 PM" src="https://user-images.githubusercontent.com/427398/225746510-bc333870-a94c-4204-a0fc-6b9af241be78.png">

I have confirmed that this is not the case in the DB or Route53, it only happens in the UI.  I think it's probably due to how we're doing the UI to show the subdomain with a different colour.

cc @Myrfion

**Comment by Myrfion** [comment]
resolved in #369
