### ISSUE TITLE
Create user dashboard pages design

### ISSUE THREAD

**Issue by Myrfion** [DevelopingSpace/starchart#36]
It would be great to have some designed wireframes on our front end, for now it least for our users. This is what wiki says on front-end user dashboard functionalities: 
User Dashboard page with a way to create or manage subdomains and certificates:
- User can create new subdomains (A, AAAA, CNAME)
- User can view existing subdomains
- User can update existing subdomains
- User can delete existing subdomains
- User can renew a subdomain for an additional period of time (e.g., add another 6 months)
- User can create a wildcard certificate
- User can view wildcard certificate and private key
- User can get instructions on how to use the certificate
- User can revoke wildcard certificate
- User can renew wildcard certificate

In my opinion, it would be great to have the following pages:
- /dashboard - which is overall info, which could be the number of subdomains and some other general info, stats etc
- /subdomains - list of subdomains (probably table) and button for each to delete it, it also might have functionality to prolong domain
- /subdomains/:id - edit subdomain 
- /subdomains/new - create new subdomain
- /wildcard - view and renew wildcard 
- /wildcard/new
- /wildcard/instructions

Charka UI has this [Figma template](https://www.figma.com/community/file/971408767069651759) and since we use it on our front end it makes sense to use it for the design too.

**Comment by dadolhay** [comment]
#58 is part of this (subset)
