### ISSUE TITLE
How should a Route53 Delete deal with missing domain?

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#360]
In testing (and theoretically in production), we can get into a state where the MySQL database has a DNS Record, but it doesn't exist in Route53 for some reason (manually removed, error during creation, etc).

When the DNS Flow happens, we currently fail and retry the delete a few times, then fail the whole job.  However, if we are trying to delete a DNS Record, and it isn't there, the job could actually pass.

We need to decide on how to deal with this case.  I'm wanting to not have orphaned records in the DB that we can't delete via automation because they are only partially created.

cc @Genne23v, @dadolhay, @SerpentBytes

**Comment by Genne23v** [comment]
If we need to allow someone to manually remove the record in Route53, I think we should regularly run the background job if all the records in DB exist in Route53. 
Or we provide the admin function to always remove DB and Route53 together.

**Comment by humphd** [comment]
It's always going to be possible that a Route53 record is already deleted when we try to do our delete flow, since the AWS hosted zone is administered separately from our app.  So I think we should not fail if we are already in the desired state (i.e., record does not exist during delete).
