### ISSUE TITLE
Error in UI if DNS record value is wrong

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#372]
We were testing staging today, and notice that you can create an invalid DNS value in the UI:

![image](https://user-images.githubusercontent.com/427398/225981342-ef45c280-4cf5-4ed5-88b0-979dd9ed02c2.png)

We should stop the user from submitting an invalid value when they enter a new record.  Each record type has its own set of rules we could enforce with some JS.

**Comment by humphd** [comment]
Also, it looks like we allow a CNAME that's invalid:

![image](https://user-images.githubusercontent.com/427398/225982592-224ef337-51c0-4f4c-8e4a-79e8db47e7cd.png)

**Comment by Eakam1007** [comment]
Is this the same as #277 ?
