### ISSUE TITLE
Add release management instruction for sheriff

### ISSUE THREAD

**Issue by cychu42** [DevelopingSpace/starchart#392]
I have noticed new sheriffs asking about how to handle releases a few times, so we should add some explanations/links of how to use `npm version` and [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) in the [sheriff page](https://github.com/Seneca-CDOT/dps911-osd700-winter-2023/wiki/How-to-be-a-Sheriff).

**Comment by SerpentBytes** [comment]
> We also need someone to finish #269.

I could work on #269 if no one else is interested.

**Comment by cychu42** [comment]
An addition is made on how to create releases, see [here](https://github.com/Seneca-CDOT/dps911-osd700-winter-2023/wiki/How-to-be-a-Sheriff#creating-releases).
Let me know if it looks good or you want any changes.

**Comment by cychu42** [comment]
I'm going to close issue for now, after having Mario saw it and no further change is suggested so far.
