### ISSUE TITLE
Switch to subdomain vs. name in dns.server.ts functions

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#399]
In app/lib/dns.server.ts we have lots of places that use `name` for what we now call `subdomain` in other parts of the tree.  For example:

```ts
export const createRecord = (username: string, type: RecordType, name: string, value: string) => {
```

For consistency, let's move to using `subdomain`.

**Comment by Genne23v** [comment]
This issue is resolved by #417
