### ISSUE TITLE
First run experience for DNS Records page

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#403]
The first time you use the site and go to the DNS Records, you're met with this empty table:

<img width="1193" alt="Screenshot 2023-03-21 at 4 56 21 PM" src="https://user-images.githubusercontent.com/427398/226738951-b6e65665-e624-4abf-a8c6-29d5d56d2875.png">

Let's not show the table when the user has no records, and instead show some text in the centre with the "Create" button that says something like, "Create your first DNS Record!"

cc @Ririio, @Myrfion

**Comment by Eakam1007** [comment]
@humphd, is this something similar to what you had in mind for this?
<img width="954" alt="image" src="https://user-images.githubusercontent.com/67077705/227374433-d54867c9-c249-4d75-a22d-76a0bf159e75.png">

**Comment by humphd** [comment]
Yeah, that's great!

**Comment by Eakam1007** [comment]
Perfect, I will create a PR
