### ISSUE TITLE
Add coverage report for playwright e2e tests

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#420]
We have added coverage report for unit tests in #410.
We should also add coverage report for e2e tests, which use playwright. This could potentially be done by using [playwright-test-coverage](https://www.npmjs.com/package/playwright-test-coverage) module.

**Comment by Eakam1007** [comment]
After looking at the playwright-test-coverage module, seems like it requires `babel-plugin-istanbul` to work. Not sure if this is even possible with our Remix stack

**Comment by humphd** [comment]
If you can't do the playwright stuff, don't worry it's not critical.  Tests are more important than coverage about tests.  Focus on those.
