### ISSUE TITLE
New DNS Record should only allow letters, digits and hyphen for name

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#437]
Today on staging, we ran into an issue where Let's Encrypt refuses to allow any name with underscores.  Doing a bit of digging, we found that they only support **letters, digits, and hyphens**.  Route53 supports more than this, but let's limit the names that our users can enter to only allow letters, digits, and hyphens.

More details here https://community.letsencrypt.org/t/underscore-in-subdomain-fails/31431/6

**Comment by Genne23v** [comment]
This issue can be closed without action
