### ISSUE TITLE
Sort DNS Records such that multiple records with same name are grouped

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#442]
In #438 we are moving to allow DNS Records of type `A`, `AAAA`, and `TXT` (i.e., not `CNAME`) to have multiple values.  Our current UI assumes this is always a single value.  We need to make 2 changes:

1. DNS Records table needs to be able to show one or more values.  We could join them with `,` for example
2. The New DNS Record and Edit DNS Record form needs to allow for one or more input boxes for the value(s).  You should be able to add or remove input boxes to include multiple values.  By default we'd show only 1.

**Comment by Myrfion** [comment]
@cychu42 sorry just seen your message on this one, the issue got resolved in your PR right?

**Comment by humphd** [comment]
When a user has more than 1 record with the same name and different type, it would be nice to "group" them together by sorting the results:

<img width="1233" alt="Screenshot 2023-04-10 at 11 20 45 AM" src="https://user-images.githubusercontent.com/427398/230931611-77c79a8c-1fe2-4e3a-a8c4-1a0699762df1.png">

**Comment by dadolhay** [comment]
```js
const recordsSorted = records.sort(
  (({subdomain: aSubdomain, type: aType}, {subdomain: bSubdomain, type: btype}) =>
    [...aSubdomain].reverse().join('').localeCompare([...bSubdomain].reverse().join('')) ||
    atype.localeCompare(btype)
  );
```
- reverse both subdomains
- compare them
- If equal, then compare the record type the same way

This is not tested, you might need to change the compare order (like compare b with a instead of a with b)

**Comment by cychu42** [comment]
> @cychu42 sorry just seen your message on this one, the issue got resolved in your PR right?

I only added restriction to not duplicate CNAME records.
