### ISSUE TITLE
Certificate loses newlines

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#453]
From ITS testing on staging:

> Copy/paste certificate and key in windows, puts the entire certificate or key in one line, instead of multiple lines. I assume it’s because the newline in linux vs windows.

The PEM format requires the newlines to exist, so we need to be careful about stripping them out.  This might be simply due to us mocking the data currently?

When the certificate UI is finished, let's confirm this is working as expected on Windows.

However, let's write an e2e test for this case.

**Comment by Myrfion** [comment]
Need to verify if it is still a problem when certificates gonna be landed

**Comment by humphd** [comment]
I've tested this on staging with my Mac, and we're losing the `\n` for sure.  We should figure out where we lose them.  I'm not sure that they are even in the database, tbh.

Also, if you test this on staging, we seem to render 4 copies of the private key and certificate in the UI, so there are a number of bugs here to sort out.

<img width="914" alt="Screenshot 2023-03-30 at 10 32 40 PM" src="https://user-images.githubusercontent.com/427398/229008349-2b4c01b8-9cf6-466f-a420-e25f794cd3ec.png">

**Comment by humphd** [comment]
For reference, here is what it should look like, and what we're trying to achieve:

![image](https://user-images.githubusercontent.com/427398/229009073-d5458cbc-5d28-42e6-a531-4b637ed9d726.png)

Fix-width font, line breaks, etc.  This is what you should get when you a) download; b) copy to clipboard; c) show/hide.

**Comment by Ririio** [comment]
![image](https://user-images.githubusercontent.com/32577022/229016274-63fca9d9-4baa-4c25-9032-2f78a80dbdb5.png)

This is how you want it to look right?

**Comment by Ririio** [comment]
> I've tested this on staging with my Mac, and we're losing the `\n` for sure. We should figure out where we lose them. I'm not sure that they are even in the database, tbh.
> 
> Also, if you test this on staging, we seem to render 4 copies of the private key and certificate in the UI, so there are a number of bugs here to sort out.
> 

Tested this on windows, and copy seems to be working as intended, and rendering works fine after adding a couple of things on the style

![image](https://user-images.githubusercontent.com/32577022/229017708-6cff4d0f-4dc0-4a5d-a76e-468c97a8bcae.png)

Not quire sure why it's duplicating though...

**Comment by humphd** [comment]
Can you do a PR to add these changes?  That looks great.  We can deal with the repetitions in a different PR.

**Comment by Eakam1007** [comment]
Is this resolved now?

**Comment by humphd** [comment]
Indeed.
