### ISSUE TITLE
Inconsistent left and top margins across pages

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#488]
We should use the same left and top margins across our various pages.  Right now, moving between them feels weird, since things move around.

I think this is possibly happening due to the DNS Records table wanting more width?  We should figure out a solution for consistency.

<img width="1081" alt="Screenshot 2023-03-31 at 8 37 55 AM" src="https://user-images.githubusercontent.com/427398/229122478-aa541e8b-0eae-4e9b-b66d-b4bc8da066cd.png">

**Comment by Eakam1007** [comment]
We should probably move the margins out of individual pages, and put a common margin inside the shared layout route which also renders the header on all these pages

**Comment by humphd** [comment]
Adding the Admin page to the mix, which is different yet again:

<img width="1933" alt="Screenshot 2023-04-02 at 11 13 58 AM" src="https://user-images.githubusercontent.com/427398/229361982-08fea321-c818-44df-afff-5f20e8bd2fce.png">
