### ISSUE TITLE
Confirm certificate received from let's encrypt

### ISSUE THREAD

**Issue by Ririio** [DevelopingSpace/starchart#490]
The certificate seems to be rendering duplicates of itself as can be seen here

![image](https://user-images.githubusercontent.com/32577022/229137642-8f6b23a5-0986-4164-9db0-5414219ce26e.png)

Looking through the database, something seems to be occuring from the back-end for this to occur

![image](https://user-images.githubusercontent.com/32577022/229138809-50b0fc5c-d854-4306-99ac-428d5981602d.png)

**Comment by humphd** [comment]
cc @cychu42

**Comment by Eakam1007** [comment]
Small update: Seems like the first part is the user certificate, and the second part is the intermediate certificate

**Comment by humphd** [comment]
From the [LE forums](https://community.letsencrypt.org/t/public-and-private-keys/25493/3):

> - cert.pem is the certificate for your domain and, among others, contains your public key;
> - chain.pem contains the intermediate certificate, the certificate from Let’s Encrypt containing the public key which is “coupled” to the private key which signed your certificate (the one above). This intermediate certificate is required for clients to verify your certificate;
> - fullchain.pem is a concatenation of cert.pem and chain.pem in one file. In most servers you’ll specify this file as the certificate, so the entire chain will be send at once. Some clients require you to specify the above two files separate. In that case you won’t need fullchain.pem;
> - privkey.pem is, no shocker here, your private key, linked to the public key which is stored in your certificate.

So it sounds like we are showing users the `fullchain.pem` and `privkey.pem`.  That is probably OK, but we could explain it.

@dadolhay does this match your understanding, too?

**Comment by Ririio** [comment]
> From the [LE forums](https://community.letsencrypt.org/t/public-and-private-keys/25493/3):
> 
> 
> 
> > - cert.pem is the certificate for your domain and, among others, contains your public key;
> 
> > - chain.pem contains the intermediate certificate, the certificate from Let’s Encrypt containing the public key which is “coupled” to the private key which signed your certificate (the one above). This intermediate certificate is required for clients to verify your certificate;
> 
> > - fullchain.pem is a concatenation of cert.pem and chain.pem in one file. In most servers you’ll specify this file as the certificate, so the entire chain will be send at once. Some clients require you to specify the above two files separate. In that case you won’t need fullchain.pem;
> 
> > - privkey.pem is, no shocker here, your private key, linked to the public key which is stored in your certificate.
> 
> 
> 
> So it sounds like we are showing users the `fullchain.pem` and `privkey.pem`.  That is probably OK, but we could explain it.
> 
> 
> 
> @dadolhay does this match your understanding, too?

How would we know which one of the certificate is which?

**Comment by Eakam1007** [comment]
I decoded the certificate with an online tool, and it gave me a common name of `Pebble Intermediate CA 345aaa` for the second one. The first one had `*.user3.starchart.com`

**Comment by humphd** [comment]
@Eakam1007 right, that makes sense.  So it's the cert + intermediate cert (Pebble is our Let's Encrypt in dev).

**Comment by Eakam1007** [comment]
#524 is related to this
