### ISSUE TITLE
Test Certificate UI flow, confirm it works on staging

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#494]
I'm trying the Certificate UI on staging, and it seems to hang with no update screen:

<img width="1075" alt="Screenshot 2023-04-01 at 2 28 12 PM" src="https://user-images.githubusercontent.com/427398/229308247-4a526594-f371-4f2a-b14b-1a03c33d5ced.png">

The Request a Certificate button is disabled, but nothing else happens.  If I refresh, it comes back to the same screen, but the button is now enabled.

I haven't check the logs yet, but this doesn't seem to be working?

cc @Ririio

**Comment by humphd** [comment]
When I wait a min, and refresh, it looks like it did work:

<img width="1012" alt="Screenshot 2023-04-01 at 2 30 30 PM" src="https://user-images.githubusercontent.com/427398/229308330-73a2ea33-c592-4497-9065-45a85d5184cd.png">

So maybe the bug here is the "pending" state UI not showing.

**Comment by Ririio** [comment]
Odd I never had this bug before, I'll look through it

**Comment by Ririio** [comment]
@humphd I found the issue, for some reason `certificate.server.ts` reverted to only returning certificate that are `issued`. I'm not sure how it happened

**Comment by Ririio** [comment]
It seems that there was a conflict with certificate between my PR and [this](https://github.com/DevelopingSpace/starchart/pull/451/files#diff-09e23cf8b6b305b3adc79e7ec861a7367b24638e8638db0fc771443874982b93), which reverted the current state of certificate by accident
