### ISSUE TITLE
Missing (*) at certificate request page

### ISSUE THREAD

**Issue by Ririio** [DevelopingSpace/starchart#526]
We need to add an (*) at the beginning of the domain name: `*.user1.starchart.com`, to specify that this certificate will work with all dns-record from the same user

![image](https://user-images.githubusercontent.com/32577022/230153759-a9316ede-004d-464f-bb1a-6622fd0613f7.png)

**Comment by humphd** [comment]
Same issue with notification email message we send:

> David Humphrey, your certificate with domain: [davidhumphrey.stage.mystudentproject.ca](http://davidhumphrey.stage.mystudentproject.ca/) is ready. Log in to My.Custom.Domain to view/manage it.
