### ISSUE TITLE
Constrain the width of text on DNS Records page

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#527]
The text at the top of the DNS Records page is too wide.  It should be capped so it doesn't go beyond a third or half the page on large widths (i.e., ~10-15 words per line):

<img width="1259" alt="Screenshot 2023-04-05 at 2 06 52 PM" src="https://user-images.githubusercontent.com/427398/230166527-367579b0-9111-47af-b11c-946fbb9dd6da.png">

**Comment by humphd** [comment]
Fixed by #541, right?

**Comment by Eakam1007** [comment]
Yup
