### ISSUE TITLE
Add horizontal margin/padding on Certificate page

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#543]
The text on the certificate page touches the border on smaller screen sizes. Here is a screenshot for iPhoneXR
<img width="200" alt="image" src="https://user-images.githubusercontent.com/67077705/230634581-6bfbb988-deee-490c-acb4-2b4337a5af8e.png">

We should probably add a margin or padding so there is some space between the edge of the screen and the text

**Comment by humphd** [comment]
Did #541 not fix this?  cc @Genne23v

**Comment by Genne23v** [comment]
> Did #541 not fix this? cc @Genne23v

We have a proper margin in all the pages now, but
