### ISSUE TITLE
De-active User button in Admin table does nothing

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#580]
We have a button to de-active a user in `app/components/admin/users-table.tsx`, but it does nothing.  This needs to get fixed before 1.0a.

**Comment by humphd** [comment]
Steps:

1. Delete the user record, which will delete all associated records in other tables (via cascade in prisma schema)
2. Trigger the reconciler to run again next time: `await` this https://github.com/DevelopingSpace/starchart/blob/4aa771f03ee52d3750077f2356c09ec4127f9898/app/models/system-state.server.ts#L37 and pass `true`

**Comment by sfrunza13** [comment]
Lines 62 onwards in user.server.ts delete user by username

export async function deleteUserByUsername(username: PrismaUser['username']) {
  return prisma.user.delete({ where: { username } });
}

**Comment by humphd** [comment]
Did this not get closed by #607?  @Myrfion why is this issue still open?

**Comment by Myrfion** [comment]
My bad, I attached some older issue to that PR, closing this one, was resolved in #607
