### ISSUE TITLE
Change "Manage" to "Create" dynamically on landing page

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#599]
During user testing, users were confused about your use of the word "Manage..." for the "Manage DNS Records" and "Manage Certificate" buttons, when they didn't have either.

We should set the text dynamically based on whether the user has any DNS Records or Certificate yet:

- If a user has no DNS Records: "Create DNS Record", otherwise "Manage DNS Records"
- If a user has no Certificate: "Create Certificate", otherwise "Manage Certificate"

**Comment by SerpentBytes** [comment]
I think I can handle this.
