### ISSUE TITLE
Do not require a `build` step before `dev`

### ISSUE THREAD

**Issue by dadolhay** [DevelopingSpace/starchart#60]
The current setup (probably because of the run-p causes a race condition) require a build step before dev successfully runs.

We should alter the script so it completes correctly even on the first time `dev` is executed

**Comment by humphd** [comment]
I wonder if we should update the [setup script](https://github.com/Seneca-CDOT/starchart/blob/main/package.json#L22) so it does this properly for people.  It's already using `run-s` so it won't race.  We'd just have to put the steps in the right order in there.

After that, it should allow the other steps to run in parallel as they do now.

**Comment by humphd** [comment]
Filed an issue upstream https://github.com/remix-run/blues-stack/issues/159

**Comment by humphd** [comment]
This is no longer required with the delay I added.  Not perfect, but way better.
