### ISSUE TITLE
Error when ending impersonation of user after deleting DNS Record

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#622]
Saw this while testing stuff on one of my branches after I ended impersonation. Confirmed that this also happens on current main. This does not have much impact, as you can click the `Go to Home` button and end impersonation normally.

<img width="961" alt="error" src="https://user-images.githubusercontent.com/67077705/232233200-0c5e9ab5-ced8-47fe-89a9-38783d041b38.png">

### Steps to replicate
- Login as admin
- Impersonate a user
- Create a DNS Record (optional - or delete an existing DNS Record)
- Delete the DNS Record
- End Impersonation
- Check for above error

### Video walkthrough

https://user-images.githubusercontent.com/67077705/232233953-535a9136-e1c5-43aa-9b32-1efdc7674413.mp4

**Comment by humphd** [comment]
cc @sfrunza13.  So we're trying to end impersonation on a route that we didn't intend?  We should probably give an explicit action URL for the one we want that form to submit to when clicked.

**Comment by sfrunza13** [comment]
> cc @sfrunza13. So we're trying to end impersonation on a route that we didn't intend? We should probably give an explicit action URL for the one we want that form to submit to when clicked.

I remember putting the action in root.tsx, I will do as you mentioned and specify it.
