### ISSUE TITLE
Encrypt private key in database

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#81]
For a user's certificates, we're going to store both the certificate and private key.  The latter we need to encrypt.  We need a solution for doing this.

As I understand it, we have 3 options:

- do it in MySQL (i.e., at the database level).  Much of what I read suggests not doing this, but I'm not an expert.
- do it in Prisma middleware, for example https://github.com/47ng/prisma-field-encryption
- do it in the server code before we write to the db

We should evaluate these options (and maybe others?) and implement a solution.

**Comment by cychu42** [comment]
For option 1, it seems possible to do automatic encryption on MySQL side by setting triggers to run [`AES_ENCRYPT()`](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-encrypt) on each update and insert.
https://stackoverflow.com/questions/50348954/safely-auto-encrypt-mysql-column-using-a-trigger-with-a-key-string

Although I do wonder where would the encryption key be stored in such case. Some research suggests it's safer to store on a separate machine, then the question would be how would the database get the key.

**Comment by humphd** [comment]
Thank you for researching.  I wonder if we should abandon this.  We can add it post 1.0 if that's important to ITS.

**Comment by cychu42** [comment]
I think it would make sense to ask ITS how they want to handle it, before we do anything, especially option 1 is essentially leaving it up to ITS to encrypt data and possible store that key.

**Comment by humphd** [comment]
> I think it would make sense to ask ITS how they want to handle it, before we do anything, especially option 1 is essentially leaving it up to ITS to encrypt data and possible store that key.

I asked ITS as you requested, and they agree to simplify it by keeping it in plain text in the DB for now.  Closing.
